export { default as Customers } from './Customers';
export { default as Dashboard } from './Dashboard';
export { default as Expenses } from './Expenses';
export { default as Inventory } from './Inventory';
export { default as Login } from './Login';
export { default as Reports } from './Reports';
export { default as Sales } from './Sales';
export { default as Settings } from './Settings';
export { default as UserProfiles } from './UserProfiles';
